export type TrailerShot = {
  file: string;
  title: string;
  kicker: string;
  startScale: number;
  endScale: number;
  x: number;
  y: number;
  tint: string;
};

export const shots: TrailerShot[] = [
  {
    file: "stills/still01.png",
    title: "Grid Pressure",
    kicker: "Multi-car launch setup",
    startScale: 1.08,
    endScale: 1.19,
    x: -34,
    y: 0,
    tint: "#e5252a",
  },
  {
    file: "stills/still02.png",
    title: "Pole Position Energy",
    kicker: "Low rear pursuit angle",
    startScale: 1.12,
    endScale: 1.24,
    x: 42,
    y: -16,
    tint: "#2f80ed",
  },
  {
    file: "stills/still03.png",
    title: "Full-Throttle Field",
    kicker: "Long straight, clean visibility",
    startScale: 1.02,
    endScale: 1.14,
    x: -16,
    y: 0,
    tint: "#ffcb3d",
  },
  {
    file: "stills/still04.png",
    title: "Side-By-Side Racing",
    kicker: "Pack composition for client demo",
    startScale: 1.1,
    endScale: 1.2,
    x: 0,
    y: -10,
    tint: "#e5252a",
  },
  {
    file: "stills/still05.png",
    title: "Track-Width Read",
    kicker: "Cinematic speed lane",
    startScale: 1.04,
    endScale: 1.18,
    x: -22,
    y: 8,
    tint: "#2f80ed",
  },
  {
    file: "stills/still06.png",
    title: "Race Craft",
    kicker: "AI cars staged through traffic",
    startScale: 1.08,
    endScale: 1.22,
    x: 32,
    y: -12,
    tint: "#ffcb3d",
  },
  {
    file: "stills/still07.png",
    title: "High-Speed Formation",
    kicker: "Sweeping camera pass",
    startScale: 1.12,
    endScale: 1.04,
    x: -28,
    y: 0,
    tint: "#e5252a",
  },
  {
    file: "stills/still08.png",
    title: "Wheel-To-Wheel",
    kicker: "Close race spacing",
    startScale: 1.14,
    endScale: 1.26,
    x: 18,
    y: -6,
    tint: "#2f80ed",
  },
  {
    file: "stills/still09.png",
    title: "Rear Chase",
    kicker: "Client-ready gameplay framing",
    startScale: 1.1,
    endScale: 1.2,
    x: 0,
    y: -10,
    tint: "#ffcb3d",
  },
  {
    file: "stills/still10.png",
    title: "Sponsor Detail",
    kicker: "Hero bodywork close-up",
    startScale: 1.08,
    endScale: 1.18,
    x: 44,
    y: -8,
    tint: "#e5252a",
  },
  {
    file: "stills/still11.png",
    title: "Launch Camera",
    kicker: "Immersive chase perspective",
    startScale: 1.09,
    endScale: 1.21,
    x: -10,
    y: -8,
    tint: "#2f80ed",
  },
  {
    file: "stills/still12.png",
    title: "Tactical Overview",
    kicker: "Formation clarity from above",
    startScale: 1.04,
    endScale: 1.15,
    x: 0,
    y: 0,
    tint: "#ffcb3d",
  },
  {
    file: "stills/still13.png",
    title: "Corner Entry",
    kicker: "Pack compression moment",
    startScale: 1.08,
    endScale: 1.2,
    x: -18,
    y: 0,
    tint: "#e5252a",
  },
  {
    file: "stills/still14.png",
    title: "Race Line",
    kicker: "Straight-line acceleration story",
    startScale: 1.06,
    endScale: 1.2,
    x: 22,
    y: -4,
    tint: "#2f80ed",
  },
  {
    file: "stills/still15.png",
    title: "Pack Intelligence",
    kicker: "AI grid density and spacing",
    startScale: 1.09,
    endScale: 1.22,
    x: 0,
    y: -10,
    tint: "#ffcb3d",
  },
  {
    file: "stills/still16.png",
    title: "Formula Detail",
    kicker: "Low-angle hero read",
    startScale: 1.1,
    endScale: 1.2,
    x: -36,
    y: -4,
    tint: "#e5252a",
  },
  {
    file: "stills/still17.png",
    title: "Client Demo View",
    kicker: "Dense field, clean framing",
    startScale: 1.1,
    endScale: 1.19,
    x: 36,
    y: -12,
    tint: "#2f80ed",
  },
  {
    file: "stills/still18.png",
    title: "Final Hero Car",
    kicker: "Premium closing frame",
    startScale: 1.06,
    endScale: 1.18,
    x: -24,
    y: 4,
    tint: "#ffcb3d",
  },
];
